export const FETCH_PRODUCTS_PENDING="FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_FAILED="FETCH_PRODUCTS_FAILED";
export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS";

export const CREATE_NEW_PRODUCT_PENDING="CREATE_NEW_PRODUCT_PENDING";
export const CREATE_NEW_PRODUCT_SUCCESS="CREATE_NEW_PRODUCT_SUCCESS";
export const CREATE_NEW_PRODUCT_FAILED="CREATE_NEW_PRODUCT_FAILED";

export const DELETE_PRODUCT_PENDING="DELETE_PRODUCT_PENDING";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED="DELETE_PRODUCT_FAILED";